plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1
filters:
  tag:type: webservers
hostnames:
  - dns-name
compose:
  ansible_user: "'ec2-user'"
  ansible_ssh_private_key_file: "'secrets/ssh-key.pem'"
  ansible_ssh_common_args: "'-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
